### ISSUE TITLE
НЕЗАЧЕТ

### ISSUE THREAD

**Issue by KipariS** [MaxIblis/MaxIblis.github.io#2]
9 строка - нельзя коментировать внутри тега 
32 строка -  ссылке поставить атрибут target

**Comment by MaxIblis** [comment]
Исправлены обе ошибки. 
По второй. В задании не было указано, что необходима ссылка на новое окно. Поставить target - не проблема.

**Comment by MaxIblis** [comment]
я не до конца разобрался с работой GitHub. исправил сам файл.
