### ISSUE TITLE
ЗАЧЕТ

### ISSUE THREAD

**Issue by KipariS** [MaxIblis/MaxIblis.github.io#3]
Все хорошо.
Просто запомни, на сайтах ставиться target="_blank" в 99,9%, когда ссылка ведёт на ДРУГОЙ сайт. 
А еще из рекомендаций <img/> - тегу, нужно ставить атрибут alt="альтернативный текст" 
Это на случай если картинки у пользователя отключены, вместо них выводиться содержание.
Глянь тут синтаксис - http://htmlbook.ru/html/img

**Comment by MaxIblis** [comment]
Ну в целом, да. Согласен, что когда на другой сайт ссылка, то необходимо новая вкладка. 
Буду теперь всегда использовать Target. Спасибо за советы.
